name: Dev-Terraform-Plan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Terraform-Script:
    runs-on: ubuntu-latest
    name: Run Terraform Plan with Linting and Security Checks
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            dev/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
            
      - name: Terraform Init
        working-directory: dev
        run: terraform init -upgrade 

      - name: Terraform fmt check
        working-directory: dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: dev
        run: terraform validate

      - name: Force Unlock Terraform State (if needed)
        working-directory: dev
        run: |
          # Try to get the lock ID and force unlock if locked
          if terraform plan -detailed-exitcode 2>&1 | grep -q "Error acquiring the state lock"; then
            echo "State is locked, attempting to force unlock..."
            LOCK_ID=$(terraform plan 2>&1 | grep "ID:" | awk '{print $2}' | head -1)
            if [ ! -z "$LOCK_ID" ]; then
              terraform force-unlock -force $LOCK_ID || echo "Failed to unlock, continuing anyway..."
            fi
          fi
        continue-on-error: true

      - name: Terraform Plan
        working-directory: dev
        run: terraform plan -out=tfplan
        env:
          TF_VAR_supabase_url: ${{ secrets.SUPABASE_URL }}
          TF_VAR_supabase_service_key: ${{ secrets.SUPABASE_SERVICE_KEY }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_eleven_api_key: ${{ secrets.ELEVEN_API_KEY }}
          TF_VAR_eleven_voice_id: ${{ secrets.ELEVEN_VOICE_ID }}
          TF_VAR_wp_site_url: ${{ secrets.WP_SITE_URL }}
          TF_VAR_wp_api_username: ${{ secrets.WP_API_USERNAME }}
          TF_VAR_wp_api_application_password: ${{ secrets.WP_API_APPLICATION_PASSWORD }}
          TF_VAR_google_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
